configuration-as-code: {
}
jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
    - name: "built-in"
  log: {
  }
  markupFormatter: "plainText"
  mode: NORMAL
  nodeMonitors:
    - "architecture"
    - "clock"
    - diskSpace:
        freeSpaceThreshold: "1GiB"
        freeSpaceWarningThreshold: "2GiB"
    - "swapSpace"
    - tmpSpace:
        freeSpaceThreshold: "1GiB"
        freeSpaceWarningThreshold: "2GiB"
    - "responseTime"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
appearance:
  consoleUrlProvider: {
  }
  prism:
    theme: TWILIGHT
  themeManager:
    disableUserThemes: false
    theme: "dark"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  crumb: {
  }
  prism: {
  }
  queueItemAuthenticator: {
  }
  scriptApproval:
    forceSandbox: false
  updateSiteWarningsConfiguration: {
  }
unclassified:
  administrativeMonitorsConfiguration: {
  }
  artifactManager: {
  }
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  casCGlobalConfig: {
  }
  computerRetentionCheckInterval: {
  }
  defaultView: {
  }
  envVarsFilter: {
  }
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  globalDefaultFlowDurabilityLevel: {
  }
  location:
    adminAddress: "адрес еще не настроен <nobody@nowhere>"
  myView: {
  }
  nodeProperties: {
  }
  plugin: {
  }
  pollSCM:
    pollingThreadCount: 10
  projectNamingStrategy: {
  }
  proxyConfigurationManager: {
  }
  quietPeriod: {
  }
  resourceRoot: {
  }
  scmRetryCount: {
  }
  shell: {
  }
  usageStatistics: {
  }
  viewsTabBar: {
  }
tool:
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
